Repository kreier/vex, pull requests merged in 2021-12, with the labels that each got.

#1 fix the goto function
  2021-22/2021-12-02_50p.py
Labels: bug

#3 60 lines, 70 points
  latest.py
Labels: question

#5 Extend the number of waypoints
  latest.py
Labels: enhancement

#6 130 points in just 30 seconds
  2021-22/2021-12-09_130p.py
Labels: documentation

#8 updated high scores and code
  docs/index.md
Labels: documentation
